export enum TripStatus {
  ASSIGNED = 'ASSIGNED',
  EN_ROUTE_TO_LOADING = 'EN_ROUTE_TO_LOADING',
  LOADING = 'LOADING',
  EN_ROUTE_TO_UNLOADING = 'EN_ROUTE_TO_UNLOADING',
  UNLOADING = 'UNLOADING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
